name: MakeMeAdmin
author: Xenophilicy
version: 1.2.0
description: Lets you quickly switch your role with PurePerms as a server Admin/Player/Helper/Moderator etc.
main: MakeMeAdmin\main
api: [3.0.0, 3.5.1, 4.0.0]
commands:
  mma:
    description: Quickly Change your in-game rank!
    permission: makemeadmin.use.ui
  mmadmin:
    description: Quickly Change your in-game rank!
    permission: makemeadmin.use.ui
  makemeadmin:
    description: Get info about the plugin MakeMeAdmin!
    permission: makemeadmin.use.about
permissions:
  makemeadmin.use:
    default: op
    description: Allows use of all MakeMeAdmin permissions!
    children:
        makemeadmin.use.1:
          description: Allows use of Rank 1!
          children:
            makemeadmin.use.ui:
            default: false
        makemeadmin.use.2:
          description: Allows use of Rank 2!
          children:
            makemeadmin.use.ui:
            default: false
        makemeadmin.use.3:
          description: Allows use of Rank 3!
          children:
            makemeadmin.use.ui:
            default: false
        makemeadmin.use.4:
          description: Allows use of Rank 4!
          children:
            makemeadmin.use.ui:
            default: false
        makemeadmin.use.5:
          description: Allows use of Rank 5!
          children:
            makemeadmin.use.ui:
            default: false
        makemeadmin.use.about:
          default: true