name: MakeMeAdmin
author: Xenophilicy
version: 1.0.1
description: Lets you quickly switch your role with PurePerms as a server Admin/Player/Helper/Moderator etc.
main: MakeMeAdmin\main
api: 3.0.0
commands:
 mma:
  description: Change your in-game rank quickly!
  permission: makemeadmin.use.1
 mmadmin:
  description: Change your in-game rank quickly!
  permission: makemeadmin.use.2
 makemeadmin:
  description: Get info about the plugin MakeMeAdmin!
  permission: makemeadmin.use.3
permissions:
 makemeadmin.use.1:
  default: op
 makemeadmin.use.2:
  default: op
 makemeadmin.use.3:
  default: op
