# MADE BY:
#   __    __                                          __        __  __  __                     
#  /  |  /  |                                        /  |      /  |/  |/  |                    
#  $$ |  $$ |  ______   _______    ______    ______  $$ |____  $$/ $$ |$$/   _______  __    __ 
#  $$  \/$$/  /      \ /       \  /      \  /      \ $$      \ /  |$$ |/  | /       |/  |  /  |
#   $$  $$<  /$$$$$$  |$$$$$$$  |/$$$$$$  |/$$$$$$  |$$$$$$$  |$$ |$$ |$$ |/$$$$$$$/ $$ |  $$ |
#    $$$$  \ $$    $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |$$ |$$ |$$ |      $$ |  $$ |
#  $$ /$$  |$$$$$$$$/ $$ |  $$ |$$ \__$$ |$$ |__$$ |$$ |  $$ |$$ |$$ |$$ |$$ \_____ $$ \__$$ |#
#  $$ |  $$ |$$       |$$ |  $$ |$$    $$/ $$    $$/ $$ |  $$ |$$ |$$ |$$ |$$       |$$    $$ |
#  $$/   $$/  $$$$$$$/ $$/   $$/  $$$$$$/  $$$$$$$/  $$/   $$/ $$/ $$/ $$/  $$$$$$$/  $$$$$$$ |
#                                        $$ |                                      /  \__$$ |
#                                        $$ |                                      $$    $$/ 
#                                        $$/                                        $$$$$$/  

# Command used to change groups (Leave default for PurePerms)
Group_Command: "setgroup"

# Every rank added needs a label, alias, and permission:
# Label → The label will be the text you see in the UI
# Alias → The alias is the name of the group in your groups.yml file
# Permission → Permission node required to switch to the rank

# You can use '§' or '&' in the labels for colors and effects to show up on the UI
# Add as many ranks as you'd like using this format → Label:Alias:Permission
Ranks:
  - "&l&6Owner:owr:rank.switch.owner"
  - "&l&4Admin:adm:rank.switch.admin"
  - "&l&9Moderator:mod:rank.switch.mod"
  - "&l&eHelper:hlp:rank.switch.helper"
  - "&l&aGuest:gst:rank.switch.guest"
